### ISSUE TITLE
Library Error while running.(ModuleNotFoundError)

### ISSUE THREAD

**Issue by GauravWalia19** [hardikyadav12/Wikipediasummaryaudio#6]
ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
Traceback (most recent call last):
  File "code.py", line 13, in <module>
    playsound('languageselect.mp3')
  File "/home/anonymous/anaconda3/lib/python3.6/site-packages/playsound.py", line 91, in _playsoundNix
    import gi
ModuleNotFoundError: No module named 'gi'

**Comment by GauravWalia19** [comment]
:octocat:  Hey tell me what's the issue while running...
